---
- name: "Create nginx config"
  template:
    src: templates/nginx.conf.j2
    dest: /tmp/nginx-head.conf
  become: no


- name: Setup nginx container
  docker_container:

    name: nginx
    image: nginx
    state: started
    ports: ["80:80"]
    etc_hosts:
      dockerhost: "{{ dockerhost_ip }}"
    links: "{{ r_proxies.keys() }}"
    volumes:
      - "/tmp/nginx-head.conf:/etc/nginx/nginx.conf:ro"
