---
# May need to completely remove nginx if containers it is linking to have changed...

- set_fact:
    config_dir: "{{ base_dir }}/config/nginx"

- name:    "Setup config folder"
  file:
    path:  "{{ config_dir }}"
    state: directory
    mode:  0777
  become:  yes

- name:    "Create nginx config"
  template:
    src:   templates/{{ conf_type }}.nginx.conf.j2
    dest:  "{{ config_dir }}/nginx-head.conf"
  become:  no

- name: Setup nginx container
  docker_container:

    name:  nginx
    image: nginx
    state: started
    ports: ["{{ port }}:{{ port }}"]
    etc_hosts:
      dockerhost: "{{ dockerhost_ip }}"
    links: "{{ r_proxies.keys() }}"
    volumes:
      - "{{ config_dir }}/nginx-head.conf:/etc/nginx/nginx.conf:ro"

    log_driver: splunk
    log_options:
      splunk-token: "{{ splunk_hec_token }}"
      splunk-url: http://{{ indexer_ip | default(dockerhost_ip) }}:8088
      splunk-index: diana_svc
      splunk-source: nginx