---
- name: "Create nginx config"
  template: >
    src=templates/nginx.conf.j2
    dest=/tmp/nginx-head.conf
  become: no


- name: Setup nginx container
  docker_container:

    name: nginx-head
    image: nginx
    state: started
    ports: ["80:80"]
    links:
      - orthanc_core
      - orthanc_ci0
      - orthanc_hb
      - orthanc_p3
    volumes:
      - "/tmp/nginx-head.conf:/etc/nginx/nginx.conf:ro"
#      - "/tmp/www:/etc/nginx/html:ro"

