# Simple DIANA Setup

# Orthanc Queues      814x
# Orthanc Archives    804x
# Splunk Syslog        512
# Splunk Interface    8000
# Splunk HEC          8088
# Splunk API          8089
# Postgres            5432

# IMPORTANT!  If using a splunk indexer, you need at _least_ 1GB of ram

# TODO: Add SMB mapped folder and setup Splunk monitor
# TODO: Add HEC tokens/indices automatically

# TODO: Add Front-End
#   TODO: Add GUIDMint
#   TODO: Add Uploader

# TODO: Add Indexer for Core (all data is in the same buckets)

# > ansible-playbook -i secret_inventory.yml --vault-password secret_vault_pw.txt central_im_playbook.yml

---
- name: Simple DIANA Config

#  hosts: DIANA-staging
#  hosts: localhost
  hosts:  trusty64

  vars_files:
    - secret_vault.yml

  # Required credentials for the script, include them separately in 'secrets.yml'
  vars:
    pg_admin_pw:      "{{ vault_pg_admin_pw }}"
    orthanc_db_pw:    "{{ vault_orthanc_db_pw }}"
    splunk_admin_pw:  "{{ vault_splunk_admin_pw }}"
    splunk_hec_token: "{{ vault_splunk_hec_token }}"  # just for d-mon
    orthanc_admin_pw: "{{ vault_orthanc_admin_pw }}"
    orthanc_ci_pw:    "{{ vault_orthanc_ci_pw }}"
    orthanc_hb_pw:    "{{ vault_orthanc_hb_pw }}"
    orthanc_p3_pw:    "{{ vault_orthanc_p3_pw }}"

  roles:
  - role:      orthanc
    title:     DIANA Core
    name:      orthanc_core
    api_port:  8042
    admin_pw:  "{{ orthanc_admin_pw }}"

  - role:      orthanc
    title:     Christianson Imaging
    name:      orthanc_ci0
    api_port:  8045
    admin_pw:  "{{ orthanc_ci_pw }}"

  - role:      roles/orthanc
    title:     Christianson Queue
    name:      orthanc_ci_in
    api_port:  8145
    dicom_port: 4145
    admin_pw:  "{{ orthanc_ci_pw }}"
    peers:
      orthanc_ci0:
        Url:  "http://orthanc_ci0:8042"
        Username: "orthanc"
        Password: "{{ orthanc_ci_pw }}"

  - role:      orthanc
    title:     HOBIT Imaging
    name:      orthanc_hb
    api_port:  8046
    admin_pw:  "{{ orthanc_hb_pw }}"

  - role:      roles/orthanc
    title:     HOBIT Queue
    name:      orthanc_hb_in
    api_port:  8146
    dicom_port: 4146
    admin_pw:  "{{ orthanc_hb_pw }}"
    peers:
      orthanc_hb:
        Url:  "http://orthanc_hb:8042"
        Username: "orthanc"
        Password: "{{ orthanc_hb_pw }}"

  - role:      orthanc
    title:     ProTECT III Imaging
    name:      orthanc_p3
    api_port:  8047
    admin_pw:  "{{ orthanc_p3_pw }}"

  - role: splunk

  - role: nginx

  - role: diana-utils

  - role:        monitor
    dmon_config: dmon_central2.yml