# Setup Central Imaging DIANA Stack
# Merck, Fall 2017

# TODO: splunk - Setup folder monitors automatically
# TODO: splunk - Add/Get HEC tokens/indices automatically
# TODO: splunk - pipe in _all_ logs from systems, orthanc, postgres, gunicorn, d-mon

# TODO: Frontend - Setup per-project anonymizers on ingress
# TODO: Frontend - Add Uploader

# TODO: Switch to mount volumes for DBs (so they can live in other spaces)
# TODO: Add Core Storage (all data is in the same buckets, should be able to just import them)
# TODO: Add orthanc DICOM port if applicable (to queues)
# TODO:  - Setup queue per enrolling institution to tag the data?

# TODO: Add auto-population for studies w local data
# TODO: Create RIH Research Imaging config (Beland, Atalay, Asaad proj)

# TODO: dmon.config should probably monitor {{ dockerhost_ip }} instead of eth1 or eth0??

# TODO: Omero
# TODO: JetBrains/Jira Desk

# > ansible-playbook -i secret_inventory.yml --vault-password secret_vault_pw.txt central2_playbook.yml

---
- name: Setup Central Imaging DIANA Stack

#  hosts: DIANA-staging
#  hosts: localhost
  hosts:  trusty64

  vars_files:
    - secret_vault.yml

  # Required credentials for the script, include them separately in 'secrets.yml'
  vars:
    pg_admin_pw:      "{{ vault_pg_admin_pw }}"
    orthanc_db_pw:    "{{ vault_orthanc_db_pw }}"
    splunk_admin_pw:  "{{ vault_splunk_admin_pw }}"
    splunk_hec_token: "{{ vault_splunk_hec_token }}"  # just for d-mon
    orthanc_admin_pw: "{{ vault_orthanc_admin_pw }}"
    orthanc_ci_pw:    "{{ vault_orthanc_ci_pw }}"
    orthanc_hb_pw:    "{{ vault_orthanc_hb_pw }}"
    orthanc_p3_pw:    "{{ vault_orthanc_p3_pw }}"

    # LOCAL_DIANA: true

  roles:
  - role:      orthanc
    title:     DIANA Core
    name:      orthanc_core
    api_port:  8042
    admin_pw:  "{{ orthanc_admin_pw }}"

  - role:      orthanc
    title:     Christianson Imaging
    name:      orthanc_ci0
    api_port:  8045
    admin_pw:  "{{ orthanc_ci_pw }}"

  - role:      roles/orthanc
    title:     Christianson Queue
    name:      orthanc_ci_in
    api_port:  8145
    dicom_port: 4145
    admin_pw:  "{{ orthanc_ci_pw }}"
    peers:
      orthanc_ci0:
        Url:  "http://orthanc_ci0:8042"
        Username: "orthanc"
        Password: "{{ orthanc_ci_pw }}"

  - role:      orthanc
    title:     HOBIT Imaging
    name:      orthanc_hb
    api_port:  8046
    admin_pw:  "{{ orthanc_hb_pw }}"

  - role:      roles/orthanc
    title:     HOBIT Queue
    name:      orthanc_hb_in
    api_port:  8146
    dicom_port: 4146
    admin_pw:  "{{ orthanc_hb_pw }}"
    peers:
      orthanc_hb:
        Url:  "http://orthanc_hb:8042"
        Username: "orthanc"
        Password: "{{ orthanc_hb_pw }}"

  - role:      orthanc
    title:     ProTECT III Imaging
    name:      orthanc_p3
    api_port:  8047
    admin_pw:  "{{ orthanc_p3_pw }}"

  - role: splunk

  - role: nginx
    r_proxies:
      orthanc_ci0:
        path: /christianson/
        port: 8042
      orthanc_hb:
        path: /hobit/
        port: 8042
      orthanc_p3:
        path: /protect3/
        port: 8042

  - role:        diana-tfe
    tfe_config:  central2_tfe_cfg.yml

  - role:        diana-monitor
    dmon_config: central2_dmon_cfg.yml