# Setup Central Imaging DIANA Stack
# Merck, Fall 2017

# TODO: splunk - Add/Get HEC tokens automatically
# TODO: splunk - Configure as forwarder if provided a "head"

# TODO: Orthanc - Once logging is fixed, should setup the RIH routers to work that way
# TODO: Orthanc - don't have to use osimis/plugins for ingress q's, btw
# TODO: Orthanc - Add DICOM port if applicable (to queues)
# TODO: Orthanc - Setup metadata tag for enrolling institution based on called AET
#       - See: https://groups.google.com/forum/#!topic/orthanc-users/RnDdnb3HmHg
#       - Add calledAET as metadata, set it with LUA or in uploader
#       - Collect metadata when DICOM tags are indexed

# TODO: Frontend - Setup per-project anonymizers on ingress (via dmon + tfe/guid api)

# TODO: dmon - timer per task?  supervisorctl restart to reindex?  Check dest before sending/force

# TODO: Add auto-population for studies w local data
# TODO: Create RIH Research Imaging config (Beland, Atalay, Asaad proj)

# TODO: Omero for microscopy (reminds me too much of xnat...)

# > ansible-playbook -i secret_inventory.yml --vault-password secret_vault_pw.txt central2_playbook.yml

---
- name: Setup Central Imaging DIANA Stack

  hosts: local.test
#  hosts: localhost
#  hosts:  trusty64

  vars_files:
    - secret_vault.yml

  # Required credentials for the script, include them separately in 'secrets.yml'
  vars:
    pg_admin_pw:      "{{ vault_pg_admin_pw }}"
    orthanc_db_pw:    "{{ vault_orthanc_db_pw }}"
    splunk_admin_pw:  "{{ vault_splunk_admin_pw }}"
    splunk_hec_token: "{{ vault_splunk_hec_token_staging }}"  # For d-mon, logging
    orthanc_admin_pw: "{{ vault_orthanc_admin_pw }}"
    orthanc_ci_pw:    "{{ vault_orthanc_ci_pw }}"
    orthanc_hb_pw:    "{{ vault_orthanc_hb_pw }}"
    orthanc_p3_pw:    "{{ vault_orthanc_p3_pw }}"

    # LOCAL_DIANA: true
    FRESH: true

  roles:

  - role: splunk
  # !!NEED TO ADD HEC TOKEN BY HAND!!

  # ---------------------------
  # BROWN STUDIES
  # ---------------------------

  - role:      orthanc
    title:     Christianson Imaging
    name:      orthanc_ci
    api_port:  8045
    admin_pw:  "{{ orthanc_ci_pw }}"

  - role:      roles/orthanc
    title:     Christianson Queue
    name:      orthanc_ci_in
    api_port:  8145
    dicom_port: 4145
    admin_pw:  "{{ orthanc_ci_pw }}"
    link_peers: yes
    peers:
      orthanc_ci:
        Url:  "http://orthanc_ci:8042"
        Username: "orthanc"
        Password: "{{ orthanc_ci_pw }}"

  # ---------------------------
  # NIH/NETT/SIREN STUDIES
  # ---------------------------

  - role:      orthanc
    title:     HOBIT Imaging
    name:      orthanc_hb
    api_port:  8046
    admin_pw:  "{{ orthanc_hb_pw }}"

  - role:      orthanc
    title:     HOBIT Queue
    name:      orthanc_hb_in
    api_port:  8146
    dicom_port: 4146
    admin_pw:  "{{ orthanc_hb_pw }}"
    link_peers: yes
    peers:
      orthanc_hb:
        Url:  "http://orthanc_hb:8042"
        Username: "orthanc"
        Password: "{{ orthanc_hb_pw }}"

  - role:      orthanc
    title:     ProTECT III Imaging
    name:      orthanc_p3
    api_port:  8047
    admin_pw:  "{{ orthanc_p3_pw }}"

  # ---------------------------
  # SUPPORT SERVICES
  # ---------------------------

  - role: nginx
    conf_type: tfe
    r_proxies:
      orthanc_ci:
        path: /christianson/
        port: 8042
      orthanc_hb:
        path: /hobit/
        port: 8042
      orthanc_p3:
        path: /protect3/
        port: 8042

  - role:        diana-tfe
    tfe_config:  central2_tfe_cfg.yml

  - role:        diana-monitor
    dmon_config: central2_dmon_cfg.yml







