# Simple DIANA Setup

# Splunk Syslog        512
# Splunk Interface    8080
# Splunk HEC          8089
# Orthanc DICOM        104
# Orthanc UI/API      8042
# Postgres            5432

# TODO: Add Project Archives

# TODO: Add Front-End
#   TODO: Add GUIDMint
#   TODO: Add Uploader + Anonymizer/Tagger

# TODO: Add Push from Core to Project Archive

---
- name: Simple DIANA Config
  hosts: localhost

  vars_files:
    - secrets.yml

  # Required credentials for the script, include them separately in 'secrets.yml'
  vars:
    pg_admin_pw:      "{{ vault_pg_admin_pw }}"
    orthanc_admin_pw: "{{ vault_orthanc_admin_pw }}"
    orthanc_db_pw:    "{{ vault_orthanc_db_pw }}"
    splunk_admin_pw:  "{{ vault_splunk_admin_pw }}"

  tasks:

  - name: Setup persistent data
    docker_container:
      name: data
      image: busybox
      state: started
      volumes:
        - /var/lib/postgresql/data
        - /var/lib/orthanc/db
        - /opt/splunk/etc
        - /opt/splunk/var

  - name: Setup db container
    docker_container:
      name: postgres
      image: postgres
      state: started
      volumes_from: data
      ports:
        - "5432:5432"
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "{{ pg_admin_pw }}"
    notify: "wait_for_postgres"

  - name: "Setup orthanc db in postgres"
    postgresql_db: "name=diana
                    state=present
                    login_host=localhost
                    port=5432
                    login_user=postgres
                    login_password={{ pg_admin_pw }}"

  - name: "Setup orthanc user for db in postgres"
    postgresql_user: "db=diana
                     name=orthanc
                     password={{ orthanc_db_pw }}
                     state=present
                     login_host=localhost
                     port=5432
                     login_user=postgres
                     login_password={{ pg_admin_pw }}"

  - name: "Create orthanc config"
#    sudo: True
    template: >
      src=orthanc.json.j2
      dest=/tmp/orthanc.json
    become: no
    notify: restart_orthanc

  - name: Setup orthanc core container
    docker_container:

      name: orthanc
      image: osimis/orthanc
      state: started

      links: postgres
      ports: ["104:4242", "8042:8042"]
      volumes_from: data
      volumes:
        - "/tmp/orthanc.json:/etc/orthanc/orthanc.json:ro"

      env:
        NAME: DIANA Core
        PLUGINS_BUNDLE_DEFAULTS: false


  - name: Setup splunk index container
    docker_container:

      name: splunk
      image: splunk/splunk

      ports: ["8080:8000", "8088:8088", "514:1514"]
      volumes_from: data

      env:
        SPLUNK_START_ARGS:  "--accept-license"
        SPLUNK_ADD: "tcp 1514"
        SPLUNK_CMD: "edit user admin -password {{ splunk_admin_pw }} -role admin -auth admin:changeme"

  handlers:
    - name: "wait_for_postgres"
      wait_for: port=5432 delay=3

    - name: restart_orthanc
      docker_container:
        name: orthanc
        state: stopped
      ignore_errors: yes  # Might not exist yet
