---
- name: Add supervisor-dmon.conf to supervisord
  copy:
    src:   templates/supervisor-dmon.conf
    dest:  /etc/supervisor/conf.d/dmon.conf
  become:  yes

- name: Copy d-mon config
  template:
    src:   "{{ dmon_config }}"
    dest:  /tmp/dmon_cfg.yml

- name: Run d-mon deamon
  supervisorctl:
    name:  d-mon
    state: restarted
  become:  yes