---
- name: Setup db container
  docker_container:
    name:  postgres
    image: postgres
    state: started
    volumes_from: data
    ports:
      - "5432:5432"
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "{{ pg_admin_pw }}"

    log_driver: splunk
    log_options:
      splunk-token: "{{ splunk_hec_token }}"
      splunk-url: http://{{ indexer_ip | default(dockerhost_ip) }}:8088
      splunk-index: diana_svc
      splunk-source: postgres

  notify: "wait_for_postgres"

# Force wait if necessary
- meta: flush_handlers