# IMPORTANT!  If using Splunk, you need at _least_ 1GB of ram
# Vagrant has only 500MB out of the box

---
- name: Setup splunk index container
  docker_container:

    name: splunk
    image: splunk/splunk
    state: started

    ports: ["8000:8000", "8088:8088", "8089:8089", "514:1514"]
    volumes_from: data

    env:
      # Answer yes accepts presumptive upgrade
      SPLUNK_START_ARGS:  "--accept-license --answer-yes"
      SPLUNK_ADD: "tcp 1514"
      SPLUNK_CMD: "edit user admin -password {{ splunk_admin_pw }} -role admin -auth admin:changeme"
