---
- name:   Copy trial front-end interface config
  copy:
    src:  "{{ tfe_config }}"
    dest: /tmp/tfe_cfg.yml

- name: Add supervisor-gunicorn.conf to supervisord
  template:
    src:  templates/supervisor-gunicorn.conf
    dest: /etc/supervisor/conf.d/gunicorn.conf
  become: yes

- name: Run gunicorn deamon
  supervisorctl:
    name: gunicorn
    state: restarted
  become: yes
#  environment:
#    tfe_config: /tmp/tfe_cfg.yml

# Manually:
# /usr/src/DIANA/utilities/tfe$ tfe_config=/tmp/tfe_cfg.yml gunicorn -b 0.0.0.0:5000 diana-tfe:app

