---
- name: Install packages
  package:
    name: supervisor
    state: present
  become: yes
  when: FRESH is defined

- name: Install pip packages
  pip: name={{ item }}
  become: yes
  with_items:
    - flask
    - flask_restplus
    - jinja2
    - markdown
    - gunicorn
    - requests
    - pyyaml
  when: FRESH is defined

- name: Install DIANA-Utils from local
  copy:
    src:  ../../DIANA/utilities
    dest: /usr/src/DIANA
  become: yes
  when: false # LOCAL_DIANA is defined

- name: Install DIANA-Utils from github
  git:
    repo: https://github.com/derekmerck/DIANA
    dest: /usr/src/DIANA
    force: yes
  become: yes
  when: LOCAL_DIANA is not defined

