---
- name: "Setup {{ name }} db in postgres"
  postgresql_db: "name={{ name }}
                  state=present
                  login_host=localhost
                  port=5432
                  login_user=postgres
                  login_password={{ pg_admin_pw }}"

- name: "Setup orthanc user for db in postgres"
  postgresql_user: "db={{ name }}
                   name=orthanc
                   password={{ orthanc_db_pw }}
                   encrypted=yes
                   state=present
                   login_host=localhost
                   port=5432
                   login_user=postgres
                   login_password={{ pg_admin_pw }}"

- name: "Setup data folder"
  file:
    path:  /data/orthanc/db
    state: directory
    mode:  0777
  become: yes

- name: "Create {{ name }} config"
#    sudo: True
  template: >
    src=templates/orthanc.json.j2
    dest=/data/orthanc/{{ name }}.json
  become: no
  notify: restart_orthanc

# Force stop if necessary
- meta: flush_handlers

- name: Setup {{ name }} container
  docker_container:

    name: "{{ name }}"
    image: osimis/orthanc
    # On RHEL, this _may_ need to be ["--logdir...", "config.json"]
    # command: ["--verbose /etc/orthanc/orthanc.json"]

    state: started
    links: "{{ ['postgres'] if peers=={} else ['postgres']+peers.keys() }}"

    ports: ["{{ api_port }}:8042"]
    volumes_from: data
    volumes:
      - "/data/orthanc/{{ name }}.json:/etc/orthanc/orthanc.json:ro"
      - "/data/orthanc/db:/var/lib/orthanc/db"

    log_driver: splunk
    log_options:
      splunk-token: "{{ splunk_hec_token }}"
      splunk-url: http://{{ dockerhost_ip }}:8088
      splunk-index: diana_svc
      splunk-source: "{{ name }}"

    env:
      PLUGINS_BUNDLE_DEFAULTS: false


